# Generated by Django 6.0 on 2025-12-08 22:20

import ModuloBoletas.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Boleta')),
                ('nombre', models.CharField(help_text='Nombre completo del cliente', max_length=200, verbose_name='Nombre del Cliente')),
                ('rut', models.CharField(db_index=True, help_text='RUT en formato XX.XXX.XXX-X', max_length=12, validators=[ModuloBoletas.models.validar_rut_chileno], verbose_name='RUT')),
                ('direccion', models.CharField(help_text='Dirección del domicilio', max_length=500, verbose_name='Dirección')),
                ('fecha_emision', models.DateField(db_index=True, help_text='Fecha de emisión de la boleta', verbose_name='Fecha de Emisión')),
                ('periodo_facturacion', models.CharField(blank=True, help_text='Ejemplo: 2025-11, 2025-12', max_length=20, verbose_name='Período de Facturación')),
                ('consumo', models.DecimalField(decimal_places=2, help_text='Consumo en metros cúbicos', max_digits=10, verbose_name='Consumo (m³)')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total a pagar en pesos chilenos', max_digits=10, verbose_name='Monto Total')),
                ('lectura_anterior', models.DecimalField(blank=True, decimal_places=2, help_text='Lectura del medidor del período anterior', max_digits=10, null=True, verbose_name='Lectura Anterior (m³)')),
                ('lectura_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Lectura del medidor actual', max_digits=10, null=True, verbose_name='Lectura Actual (m³)')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha límite de pago', null=True, verbose_name='Fecha de Vencimiento')),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='pendiente', max_length=20, verbose_name='Estado de Pago')),
                ('imagen_boleta', models.ImageField(blank=True, help_text='Imagen escaneada o fotografía de la boleta', null=True, upload_to='boletas/imagenes/', verbose_name='Imagen de la Boleta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación en Sistema')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la boleta', verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'ordering': ['-fecha_emision'],
                'indexes': [
                    models.Index(fields=['-fecha_emision'], name='ModuloBolet_fecha_e_4832f8_idx'),
                    models.Index(fields=['rut'], name='ModuloBolet_rut_e023da_idx'),
                    models.Index(fields=['estado_pago'], name='ModuloBolet_estado__4adabe_idx'),
                    models.Index(fields=['periodo_facturacion'], name='ModuloBolet_periodo_e9ef3b_idx')
                ],
                'unique_together': {('rut', 'periodo_facturacion')},
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID de Sesión')),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('recolectando_datos', 'Recolectando Datos'), ('consultando', 'Consultando'), ('comparando', 'Comparando Boletas'), ('finalizada', 'Finalizada'), ('abandonada', 'Abandonada')], default='iniciada', max_length=30, verbose_name='Estado de la Conversación')),
                ('datos_recolectados', models.JSONField(default=dict, help_text='Almacena RUT, motivo de consulta, etc.', verbose_name='Datos Recolectados')),
                ('es_consulta_comparativa', models.BooleanField(default=False, help_text='Indica si el usuario está comparando boletas', verbose_name='¿Es Consulta Comparativa?')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional de la conversación', verbose_name='Metadatos')),
                ('boleta_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='ModuloBoletas.boleta', verbose_name='Boleta Principal')),
                ('boletas_comparadas', models.ManyToManyField(blank=True, help_text='Boletas involucradas en consultas comparativas', related_name='conversaciones_comparativas', to='ModuloBoletas.boleta', verbose_name='Boletas Comparadas')),
            ],
            options={
                'verbose_name': 'Conversación de Chat',
                'verbose_name_plural': 'Conversaciones de Chat',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('asistente', 'Asistente'), ('sistema', 'Sistema')], max_length=20, verbose_name='Rol')),
                ('contenido', models.TextField(verbose_name='Contenido del Mensaje')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional del mensaje (intenciones detectadas, contexto RAG, etc.)', verbose_name='Metadatos')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='ModuloBoletas.chatconversation', verbose_name='Conversación')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['-fecha_inicio'], name='ModuloBolet_fecha_i_c175cb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['estado'], name='ModuloBolet_estado_b2b36b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['timestamp'], name='ModuloBolet_timesta_4facc6_idx'),
        ),
    ]
