# Generated by Django 4.2.7 on 2025-12-08 22:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='ID de Sesión')),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('recolectando_datos', 'Recolectando Datos'), ('calculando_prioridad', 'Calculando Prioridad'), ('solicitando_contacto', 'Solicitando Contacto'), ('finalizada', 'Finalizada'), ('abandonada', 'Abandonada')], default='iniciada', max_length=30, verbose_name='Estado de la Conversación')),
                ('datos_recolectados', models.JSONField(default=dict, help_text='Almacena los datos X1-X7 mientras se recolectan', verbose_name='Datos Recolectados')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
            ],
            options={
                'verbose_name': 'Conversación de Chat',
                'verbose_name_plural': 'Conversaciones de Chat',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id_emergencia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Emergencia')),
                ('nombre_usuario', models.CharField(max_length=200, verbose_name='Nombre del Usuario')),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Número de teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('sector', models.CharField(choices=[('anibana', 'Anibana'), ('el_molino', 'El Molino'), ('la_compania', 'La Compañía'), ('el_maiten_1', 'El Maitén 1'), ('la_morera', 'La Morera'), ('el_maiten_2', 'El Maitén 2'), ('santa_margarita', 'Santa Margarita')], max_length=50, verbose_name='Sector')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Emergencia')),
                ('tipo_emergencia', models.CharField(choices=[('rotura_matriz', 'Rotura de Matriz'), ('baja_presion', 'Baja Presión'), ('fuga_agua', 'Fuga de Agua'), ('caneria_rota', 'Cañería Rota'), ('agua_contaminada', 'Agua Contaminada'), ('sin_agua', 'Sin Agua'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Emergencia')),
                ('medidor_corriendo', models.BooleanField(blank=True, help_text='Indica si el medidor está corriendo', null=True, verbose_name='¿Medidor Corriendo?')),
                ('cantidad_agua', models.CharField(blank=True, help_text='Descripción de la cantidad de agua en caso de fuga', max_length=200, null=True, verbose_name='Cantidad de Agua (Fuga)')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='emergencias/fotos/', verbose_name='Fotografía (Opcional)')),
                ('estado_emergencia', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('atendida', 'Atendida'), ('resuelta', 'Resuelta'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado de la Emergencia')),
                ('nivel_prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Nivel de Prioridad')),
                ('solicita_contacto_colaborativo', models.BooleanField(default=False, verbose_name='Solicita Datos de Contacto Colaborativo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas del personal operativo', null=True, verbose_name='Notas Internas')),
            ],
            options={
                'verbose_name': 'Emergencia',
                'verbose_name_plural': 'Emergencias',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['-fecha_creacion'], name='ModuloEmerg_fecha_c_8c6524_idx'), models.Index(fields=['estado_emergencia'], name='ModuloEmerg_estado__46dfaa_idx'), models.Index(fields=['sector'], name='ModuloEmerg_sector_2e5dd3_idx'), models.Index(fields=['nivel_prioridad'], name='ModuloEmerg_nivel_p_5f12d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('asistente', 'Asistente'), ('sistema', 'Sistema')], max_length=20, verbose_name='Rol')),
                ('contenido', models.TextField(verbose_name='Contenido del Mensaje')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional del mensaje', verbose_name='Metadatos')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='ModuloEmergencia.chatconversation', verbose_name='Conversación')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='emergencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversacion', to='ModuloEmergencia.emergencia', verbose_name='Emergencia Asociada'),
        ),
    ]
